Repository instedd/cdx, pull requests merged in 2022-04, with the labels that each got.

#1569 Fix: tiny optimizations quick wins
  app/controllers/batches_controller.rb
  app/controllers/samples_controller.rb
  app/views/batches/index.haml
  app/views/samples/index.haml
  config/routes.rb
  spec/controllers/batches_controller_spec.rb
  spec/controllers/samples_controller_spec.rb
Labels: tech-debt

#1516 Use Selenium as Capybara driver
  .github/workflows/ci.yml
  Dockerfile-dev
  Dockerfile.selenium
  Gemfile
  Gemfile.lock
  README.md
  app/views/layouts/application.html.haml
  app/views/layouts/clean.haml
  app/views/layouts/devise.haml
  app/views/layouts/messages.haml
  docker-compose.yml
  features/alert.feature
  features/incidents.feature
  features/step_definitions/alert_steps.rb
  features/support/env.rb
  features/support/page_objects/cdx_checkbox.rb
  features/support/page_objects/cdx_page_base.rb
  features/support/page_objects/cdx_page_helper.rb
  features/support/page_objects/cdx_select.rb
  features/support/page_objects/device_model_page.rb
  features/support/page_objects/device_page.rb
  features/support/page_objects/new_encounter_page.rb
  features/support/page_objects/sample_transfer_page.rb
  features/support/page_objects/user_view_page.rb
  spec/features/device_spec.rb
  spec/features/patient_spec.rb
  spec/features/performance_spec.rb
  spec/features/policy_spec.rb
  spec/features/sample_transfers_spec.rb
  spec/spec_helper.rb
  spec/support/capybara.rb
  spec/support/database_cleaner.rb
  spec/support/feature_spec_helpers.rb
Labels: dependencies, tech-debt

#1588 Fix: add timestamps to transfer packages table
  db/migrate/20220407173015_add_timestamps_to_transfer_packages.rb
  db/schema.rb
Labels: bug

#1596 Fix tableheader element type
  app/assets/stylesheets/_tables.scss
  app/views/components/_cdx_table.html.haml
Labels: bug

#1599 Move receiver and sender institutions from `SampleTransfer` to `TransferPackage`
  app/controllers/sample_transfers_controller.rb
  app/models/sample_transfer.rb
  app/models/transfer_package.rb
  db/migrate/20220408103851_add_sender_institution_to_transfer_packages.rb
  db/migrate/20220412181435_change_sample_transfers_requires_transfer_package.rb
  db/schema.rb
  spec/controllers/sample_transfers_controller_spec.rb
  spec/features/sample_transfers_spec.rb
  spec/models/sample_transfer_spec.rb
  spec/models/transfer_package_spec.rb
  spec/support/blueprints.rb
Labels: tech-debt

#1608 Refactor: remove `rescue` in `SampleTransfersController`
  app/controllers/sample_transfers_controller.rb
Labels: tech-debt
