Repository instedd/cdx, pull requests merged in 2022-03, with the labels that each got.

#1490 Fix InvitationMailer spec to parse HTML content
  spec/mailers/invitation_mailer_spec.rb
Labels: bug

#1497 Improve filter layout
  app/assets/stylesheets/_global.scss
  app/views/batches/_filters.haml
Labels: enhancement

#1501 Tiny pending_invite simplification; closes #1444
  app/controllers/institutions_controller.rb
  spec/controllers/institutions_controller_spec.rb
Labels: tech-debt

#1504 Paperclip: use HTTPS protocol for S3 buckets by default
  config/initializers/paperclip_defaults.rb
Labels: bug

#1491 Add `SampleTransfer`
  app/assets/stylesheets/_batches.scss
  app/assets/stylesheets/_global.scss
  app/assets/stylesheets/_sprites.scss
  app/controllers/sample_transfers_controller.rb
  app/controllers/samples_controller.rb
  app/models/sample.rb
  app/models/sample_transfer.rb
  app/presenters/sample_transfer_presenter.rb
  app/views/batches/index.haml
  app/views/sample_transfers/_filters.haml
  app/views/sample_transfers/index.haml
  app/views/samples/index.haml
  config/routes.rb
  db/migrate/20220221152647_create_sample_transfers.rb
  db/schema.rb
  features/support/page_objects/sample_transfer_page.rb
  spec/controllers/sample_transfers_controller_spec.rb
  spec/features/sample_transfers_spec.rb
  spec/models/sample_transfer_spec.rb
  spec/support/blueprints.rb
Labels: enhancement

#1448 [Feature] Transfer Batches and Sample between institutions
  app/assets/fonts/icomoon.eot
  app/assets/fonts/icomoon.svg
  app/assets/fonts/icomoon.ttf
  app/assets/fonts/icomoon.woff
  app/assets/javascripts/sample_transfer.js.jsx
  app/assets/javascripts/sample_transfer_confirm.js.jsx
  app/assets/stylesheets/_batches.scss
  app/assets/stylesheets/_forms.scss
  app/assets/stylesheets/_global.scss
  app/assets/stylesheets/_sprites.scss
  app/assets/stylesheets/_tables.scss
  app/controllers/application_controller.rb
  app/controllers/concerns/view_helper.rb
  app/controllers/qc_infos_controller.rb
  app/controllers/sample_transfers_controller.rb
  app/controllers/samples_controller.rb
  app/helpers/application_helper.rb
  app/models/batch.rb
  app/models/computed_policy.rb
  app/models/concerns/site_contained.rb
  app/models/concerns/specimen_role.rb
  app/models/device.rb
  app/models/encounter.rb
  app/models/qc_info.rb
  app/models/role.rb
  app/models/sample.rb
  app/models/sample_form.rb
  app/models/sample_transfer.rb
  app/models/test_result.rb
  app/presenters/sample_transfer_presenter.rb
  app/views/batches/_samples.haml
  app/views/batches/_show_samples.haml
  app/views/batches/index.haml
  app/views/qc_infos/_form.haml
  app/views/qc_infos/_show_assays.haml
  app/views/qc_infos/_show_notes.haml
  app/views/qc_infos/edit.haml
  app/views/sample_transfers/_filters.haml
  app/views/sample_transfers/index.haml
  app/views/samples/_form.haml
  app/views/samples/_index_bulk_actions_js.haml
  app/views/samples/_index_js.haml
  app/views/samples/index.haml
  config/routes.rb
  db/migrate/20220216134506_add_old_batch_number_to_samples.rb
  db/migrate/20220217152217_create_qc_infos.rb
  db/migrate/20220221152647_create_sample_transfers.rb
  db/migrate/20220222115959_add_qc_info_id_to_samples_notes_assays.rb
  db/schema.rb
  deps/cdx_core/lib/config/fields.yml
  features/support/page_objects/sample_transfer_page.rb
  features/support/page_objects/samples_page.rb
  spec/controllers/sample_transfers_controller_spec.rb
  spec/controllers/samples_controller_spec.rb
  spec/features/sample_transfers_spec.rb
  spec/models/cdx_api_elasticsearch_mapping_template_spec.rb
  spec/models/cdx_spec.rb
  spec/models/sample_transfer_spec.rb
  spec/models/subscriber_spec.rb
  spec/support/blueprints.rb
Labels: Epic

#1527 Fix: No obfuscation of `SampleTransfer#uuid` for sender
  app/presenters/sample_transfer_presenter.rb
  spec/features/sample_transfers_spec.rb
Labels: bug

#1534 Fix: Make the input field for sample transfer confirmation wider to avoid cutoff
  app/assets/javascripts/sample_transfer_confirm.js.jsx
Labels: bug

#1544 Filter sample transfers by `old_batch_number`
  app/controllers/sample_transfers_controller.rb
  spec/controllers/sample_transfers_controller_spec.rb
Labels: bug

#1545 Show `old_batch_number` for transferred samples
  app/models/sample_form.rb
  app/views/samples/_form.haml
  spec/controllers/samples_controller_spec.rb
Labels: bug

#1532 Add note about missing confirmation link for sample transfer
  app/views/sample_transfers/index.haml
Labels: enhancement

#1557 Fix filter sample transfers by `old_batch_number`
  app/controllers/sample_transfers_controller.rb
  spec/controllers/sample_transfers_controller_spec.rb
Labels: bug
