Repository instedd/cdx, pull requests merged in 2022-06, with the labels that each got.

#1683 Adapt more forms to use `CdxFormHelper`
  app/assets/stylesheets/_forms.scss
  app/models/manifest.rb
  app/views/boxes/_form.haml
  app/views/device_models/_form.haml
  app/views/devices/_form.haml
  app/views/devise/confirmations/new.html.haml
  app/views/devise/passwords/edit.html.haml
  app/views/devise/passwords/new.html.haml
  app/views/devise/registrations/edit.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/devise/unlocks/new.html.haml
  app/views/filters/_form.haml
  app/views/patients/_form.html.haml
  app/views/policies/_form.html.haml
  app/views/qc_infos/_form.haml
  app/views/qc_infos/_show_assays.haml
  app/views/qc_infos/_show_notes.haml
  app/views/roles/_form.html.haml
  app/views/sites/_form.html.haml
  app/views/sites/_show.html.haml
  app/views/subscribers/_form.html.haml
  app/views/users/_form.html.haml
  app/views/users/invitations/edit.html.haml
  spec/models/manifest_validations_spec.rb
Labels: enhancement

#1643 Add `TransferPackageController#index` action
  app/assets/fonts/icomoon.svg
  app/assets/fonts/icomoon.ttf
  app/assets/fonts/icomoon.woff
  app/assets/stylesheets/_global.scss
  app/assets/stylesheets/_sprites.scss
  app/assets/stylesheets/_transfer_packages.scss
  app/assets/stylesheets/application.scss
  app/controllers/transfer_packages_controller.rb
  app/models/transfer_package.rb
  app/presenters/transfer_package_presenter.rb
  app/views/boxes/_preview.haml
  app/views/shared/_header_nav.haml
  app/views/shared/_list.haml
  app/views/transfer_packages/_filters.haml
  app/views/transfer_packages/index.haml
  app/views/transfer_packages/show.haml
  config/routes.rb
  db/migrate/20220602170219_add_indices_to_transfer_packages.rb
  db/schema.rb
  spec/controllers/transfer_packages_controller_spec.rb
Labels: enhancement

#1702 Drop support for Rails 4.2
  .github/actions/gems-cache/action.yml
  .github/workflows/next.yml
  Gemfile
  Gemfile.lock
  Gemfile.next
  Gemfile.next.lock
  app/controllers/boxes_controller.rb
  app/controllers/devices_controller.rb
  app/controllers/sites_controller.rb
  app/controllers/users_controller.rb
  app/models/transfer_package.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/new_framework_defaults.rb
  spec/support/default_params_helper.rb
Labels: tech-debt

#1722 Strip whitespace in `BoxSelector` search field
  app/assets/javascripts/box_selector.js.jsx
  spec/features/transfer_packages_spec.rb
Labels: enhancement

#1727 Fix: can't register in development (aka can't send registration email)
  app/views/layouts/mailer.html.haml
Labels: bug
