Repository instedd/cdx, pull requests merged in 2022-05, with the labels that each got.

#1580 Add parallel_tests to run specs in parallel
  .rspec
  Gemfile
  Gemfile.lock
  Gemfile.next.lock
  config/database.yml
  config/initializers/cdx.rb
  docker-compose.yml
  lib/tasks/elasticsearch.rake
  spec/models/cdx_api_spec.rb
  spec/support/capybara.rb
  spec/support/elasticsearch_context.rb
Labels: task, dependencies

#1635 Set Paperclip Attachment's options in a Rails5-friendly way
  config/initializers/paperclip_defaults.rb
Labels: bug

#1638 Fix timing edge case in `password_reset` spec
  features/step_definitions/password_reset_steps.rb
Labels: bug

#1637 Fix migration referencing delegated `SampleTransfer#sender_institution`
  db/migrate/20220412181435_change_sample_transfers_requires_transfer_package.rb
Labels: bug

#1644 Fix `SELENIUM_URL`
  .github/workflows/test.yml
  spec/support/capybara.rb
Labels: bug

#1646 Fix multi select for bulk actions on `SamplesController#index`
  app/views/batches/index.haml
  app/views/samples/index.haml
  config/routes.rb
Labels: bug

#1625 Add `TransferPackagesController#create` action
  app/assets/javascripts/components/sample_transfer_selector.js.jsx
  app/assets/stylesheets/_sample_transfer_selector.scss
  app/assets/stylesheets/application.scss
  app/controllers/sample_transfers_controller.rb
  app/controllers/transfer_packages_controller.rb
  app/models/sample.rb
  app/models/sample_transfer.rb
  app/models/transfer_package.rb
  app/views/sample_transfers/_filters.haml
  app/views/samples/_preview.haml
  app/views/transfer_packages/_form.haml
  app/views/transfer_packages/new.haml
  config/routes.rb
  features/support/page_objects/home_page.rb
  features/support/page_objects/sample_transfer_page.rb
  features/support/page_objects/transfer_package_page.rb
  spec/controllers/transfer_packages_controller_spec.rb
  spec/features/transfer_packages_spec.rb
  spec/models/sample_transfer_spec.rb
  spec/models/transfer_package_spec.rb
  spec/support/blueprints.rb
  spec/support/feature_spec_helpers.rb
Labels: enhancement

#1652 Regression: wicked_pdf with asset pipeline (Rails 4.2)
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/pdf.scss
  app/views/layouts/pdf.html.haml
Labels: bug

#1641 [DB] Add `TransferPackage#confirmed_at`
  app/models/transfer_package.rb
  db/migrate/20220505070823_add_confirmed_at_to_transfer_packages.rb
  db/schema.rb
  spec/models/transfer_package_spec.rb
  spec/support/blueprints.rb
Labels: enhancement

#1659 Configure human attribute names in locale instead of form UI
  app/views/batches/_form.haml
  app/views/devices/_form.haml
  app/views/qc_infos/_form.haml
  app/views/samples/_form.haml
  app/views/sites/_form.html.haml
  app/views/subscribers/_form.html.haml
  app/views/transfer_packages/_form.haml
  app/views/users/_form.html.haml
  config/locales/en.yml
Labels: bug

#1653 Fix bugs in `TransferPackage#create` form
  app/assets/javascripts/components/sample_transfer_selector.js.jsx
  app/controllers/transfer_packages_controller.rb
  app/views/transfer_packages/_form.haml
  spec/controllers/transfer_packages_controller_spec.rb
  spec/features/transfer_packages_spec.rb
Labels: bug

#1665 Fix `TransferPackagesController` specs
  spec/controllers/transfer_packages_controller_spec.rb
Labels: bug

#1662 Custom form builder for attaching error messages to fields
  app/assets/stylesheets/_errors.scss
  app/assets/stylesheets/_forms.scss
  app/helpers/application_helper.rb
  app/helpers/cdx_form_helper.rb
  app/views/batches/_form.haml
  app/views/form_builder/_field.haml
  app/views/form_builder/_field_errors.haml
  app/views/form_builder/_form_errors.haml
  app/views/institutions/_form.haml
  app/views/samples/_form.haml
  app/views/transfer_packages/_form.haml
  config/application.rb
  spec/helpers/cdx_form_helper_spec.rb
Labels: enhancement

#1655 Fix `TransferPackageController#create` to update sample status
  app/models/batch.rb
  app/models/sample.rb
  app/models/transfer_package.rb
  spec/controllers/transfer_packages_controller_spec.rb
  spec/models/sample_spec.rb
  spec/models/transfer_package_spec.rb
  spec/support/blueprints.rb
Labels: bug

#1675 Fix: WickedPDF skips CSS in production
  app/views/boxes/barcode.pdf.haml
  app/views/layouts/pdf.html.haml
  app/views/samples/barcode.pdf.haml
Labels: bug

#1666 Add `CdxFormBuilder#form_actions`
  app/helpers/cdx_form_helper.rb
  app/views/batches/_form.haml
  app/views/form_builder/_form_actions.haml
  app/views/institutions/_form.haml
  app/views/samples/_form.haml
  app/views/transfer_packages/_form.haml
Labels: enhancement

#1679 Fix: samples form has wrong indentation
  app/views/samples/_form.haml
Labels: bug

#1691 Use `date_field` for `date_produced` form field
  app/assets/stylesheets/_forms.scss
  app/controllers/concerns/view_helper.rb
  app/models/concerns/date_produced.rb
  app/models/qc_info.rb
  app/views/batches/_form.haml
  app/views/qc_infos/_form.haml
  app/views/samples/_form.haml
Labels: enhancement

#1694 Refactor `TransferPackage` to transfer boxes instead of samples
  app/assets/javascripts/box_selector.js.jsx
  app/assets/javascripts/components/sample_transfer.js.jsx
  app/assets/javascripts/sample_transfer_confirm.js.jsx
  app/assets/stylesheets/_box_preview.scss
  app/assets/stylesheets/_selector_list.scss
  app/assets/stylesheets/application.scss
  app/controllers/sample_transfers_controller.rb
  app/controllers/transfer_packages_controller.rb
  app/models/box.rb
  app/models/box_transfer.rb
  app/models/transfer_package.rb
  app/views/boxes/_preview.haml
  app/views/sample_transfers/index.haml
  app/views/samples/index.haml
  app/views/transfer_packages/_form.haml
  app/views/transfer_packages/new.haml
  config/routes.rb
  db/migrate/20220519121619_create_box_transfers.rb
  db/migrate/20220519135949_change_box_institution_null.rb
  db/schema.rb
  features/support/page_objects/samples_page.rb
  features/support/page_objects/transfer_package_page.rb
  spec/controllers/sample_transfers_controller_spec.rb
  spec/controllers/transfer_packages_controller_spec.rb
  spec/features/sample_transfers_spec.rb
  spec/features/transfer_packages_spec.rb
  spec/models/transfer_package_spec.rb
  spec/support/blueprints.rb
Labels: enhancement
